"""Clear database 02

Revision ID: 434b841c8e0c
Revises: c041b4e06ef6
Create Date: 2023-09-03 03:05:58.506423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '434b841c8e0c'
down_revision = 'c041b4e06ef6'
branch_labels = None
depends_on = None


def clear_database():
    conn = op.get_bind()
    conn.execute(sa.text("DELETE FROM dishes"))
    conn.execute(sa.text("DELETE FROM submenus"))
    conn.execute(sa.text("DELETE FROM menus"))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
