"""Clear database 03

Revision ID: 45caaaff8425
Revises: 434b841c8e0c
Create Date: 2023-09-03 03:08:09.597465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45caaaff8425'
down_revision = '434b841c8e0c'
branch_labels = None
depends_on = None


# Очистка таблиц
def clear_database():
    conn = op.get_bind()
    conn.execute(sa.text("DELETE FROM dishes"))
    conn.execute(sa.text("DELETE FROM submenus"))
    conn.execute(sa.text("DELETE FROM menus"))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    clear_database()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
