"""add_ololo_to_menu

Revision ID: dc9fa880f533
Revises: f27ea78dbdae
Create Date: 2023-09-04 20:15:44.498906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9fa880f533'
down_revision = 'f27ea78dbdae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('ololo', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menus', 'ololo')
    # ### end Alembic commands ###
