"""clear database 04

Revision ID: f27ea78dbdae
Revises: 45caaaff8425
Create Date: 2023-09-04 19:14:53.671765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f27ea78dbdae'
down_revision = '45caaaff8425'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
