"""deleye_ololo_from_menus

Revision ID: f493da1afd90
Revises: dc9fa880f533
Create Date: 2023-09-04 20:25:30.479151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f493da1afd90'
down_revision = 'dc9fa880f533'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menus', 'ololo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('ololo', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
